### ISSUE TITLE
Shade is not applied when splitting

### ISSUE THREAD

**Issue by blackheaven** [miversen33/sunglasses.nvim#7] opened 2023-11-02 14:26 UTC
When I do a `:vs`, my origin split is not shaded.

I have tried with and without `event` config (from README).

I have NeoViM 0.9.4.

**Comment by miversen33** [comment] 2023-11-02 14:31
Well that's strange. Is it safe to assume you are seeing this issue with the default settings?

**Comment by blackheaven** [comment] 2023-11-02 14:44
Yes, I have the default settings.

I have to change split to trigger the shading.

**Comment by miversen33** [comment] 2023-11-02 15:01
That's very curious. Could you provide a minimal config that reproduces this? 

An additional question, when you use the split command, does your window focus change or do you stay in the original window?

Sunglasses currently only listens for WinLeave events to initiate it's highlight changing. I hadn't thought about if a window is created but focus doesn't change. If that is your flow, that currently isn't supported (though shouldn't be difficult to add that support with a WinAdd listener or something of that nature)

**Comment by blackheaven** [comment] 2023-11-02 21:19
I'll give you one soon.

The focus is on the new split.

**Comment by blackheaven** [comment] 2023-11-02 21:27
Note: I've just tried `:vs anotherfile` it shades the first one (if there's a language server associated).

If I do `:sp` then `:vs`, it shades the second split.

**Comment by miversen33** [comment] 2023-11-03 15:32
Ya this sounds like Sunglasses getting the right event when a new window is being spawned. I will see if hooking `WinNew` as well fixes your issue.

Do note that without a configuration I can use to recreate your issue, I am very much shooting in the dark here

**Comment by miversen33** [comment] 2023-11-03 20:43
@blackheaven 

Here is a minimal configuration using lazy.nvim and running on neovim 0.9.4. Using this minimal configuration I am _not_ able to recreate your issue. This may be the work of something else interfering with Sunglasses.

That certainly doesn't mean I won't help/patch this behavior. It does however mean that without knowing what you are using, I cannot fix this issue.

Let me know if this minimal config "works" for you. Works being, when you execute `vs`, it does shade the original buffer as intended

```lua
-- Minimal configuration
-- repro.lua
-- Use with the --clean -u flags. EG nvim --clean -u repro.lua
-- This config will create a temp directory and will blow away that temp directory
-- every time this configuration is loaded. Great for simulating a new installation
-- of a plugin

-- Setting some basic vim options
-- Some junk because I am sick of formatting tables in print
local _print = _G.print
local clean_string = function(...)
    local args = { n = select("#", ...), ... }
    local formatted_args = {}
    for i=1, args.n do
        local item = select(i, ...)
        if not item then item = 'nil' end
        local t_type = type(item)
        if t_type == 'table' or t_type == 'function' or t_type == 'userdata' then
            item = vim.inspect(item)
        end
        table.insert(formatted_args, item)
    end
    return table.concat(formatted_args, ' ')
end
_G.print = function(...)
    _print(clean_string(...))
end

vim.opt.mouse = 'a'
vim.opt.termguicolors = true
-- If you want to play around with this, you can set the do_clean
-- variable to false. This will allow changes made to
-- underlying plugins to persist between sessions, while
-- still keeping everything in its own directory so
-- as to not affect your existing neovim installation.
--
-- Setting this to true will result in a fresh clone of
-- all modules
local do_clean = true
local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \
local root = vim.fn.fnamemodify("./.repro", ":p")
if vim.loop.fs_stat(root) and do_clean then
    print("Found previous clean test setup. Cleaning it out")
    -- Clearing out the mods directory and recreating it so 
    -- you have a fresh run everytime
    vim.fn.delete(root, 'rf')
end

-- DO NOT change the paths and don't remove the colorscheme

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    -- add any other plugins here
}

local sunglasses_config = {
    "miversen33/sunglasses.nvim",
    config = true,
}

table.insert(plugins, sunglasses_config)
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.opt.splitright     = true
vim.opt.splitbelow     = true

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by miversen33** [comment] 2023-11-03 21:50
Finally caught it.

```
2023-11-03 16:25:00 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE3] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:227 Ignoring Filetype change on buffer 5 as it's not a tracked sunglasses window
2023-11-03 16:25:01 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE2] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:261 Processing Window Leave
2023-11-03 16:25:01 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE3] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:269 Ignoring window 1000 as it's not a tracked sunglasses window
2023-11-03 16:25:01 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE2] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:242 Processing WinEnter
2023-11-03 16:25:01 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE3] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:247 Ignoring window 1003 as it's not a tracked sunglasses window
2023-11-03 16:25:01 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE3] -- /home/miversen/git/sunglasses.nvim/lua/sunglasses/init.lua:nil:118 Processing Window Enter Event!
2023-11-03 16:25:02 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE3] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:286 Processing Window Closed
2023-11-03 16:25:02 [Session: ugiaxvocokzpajd] [Logger: Sunglasses] [Level: TRACE2] -- ...e/miversen/git/sunglasses.nvim/lua/sunglasses/window.lua:nil:292 Attempting to delete window reference for 1003
```

What's happening was quite irritating to track down. The long short is, there seems to be a race condition between the Window wrapper creation (happening in [init.lua:113-139](https://github.com/miversen33/sunglasses.nvim/blob/main/lua/sunglasses/init.lua#L113-L139)) and the Window enter logic (happening in [window.lua:233-249](https://github.com/miversen33/sunglasses.nvim/blob/main/lua/sunglasses/window.lua#L233-L249)). This race condition means that sometimes the (on newly created windows), there is no wrapper created for the window before it tries to shade/unshade it and thus it is discarded. That is why in the logs you will see stuff like 

> Ignoring window 1000 as it's not a tracked sunglasses window

The fix is pretty obvious, make the window creation happen on window enter if there isn't a window for it already. Something I played around with before doing this but decided it would be better to have the wrapper creation happen external from the window wrapper script itself.

It seems however that events are fired asynchronously in vim (which makes sense thinking about it now) and thus my WinEnter event is being captured at normally the same time as the WinNew event which handles creating and tracking the window.

I will see if I can get a fix in place sometime this weekend as it will take a bit of cleaning/rearchitecting the window enter logic in order to do this "right".

Thank you for the issue submission! Feel free to follow the dev branch [7-shade-is-not-applied-when-splitting](https://github.com/miversen33/sunglasses.nvim/tree/7-shade-is-not-applied-when-splitting) which is where I will be uploading the fix for this (until it is tested and merged into main of course)

**Comment by miversen33** [comment] 2023-11-04 05:01
Can you try the [7-shade-is-not-applied-when-splitting](https://github.com/miversen33/sunglasses.nvim/tree/7-shade-is-not-applied-when-splitting) branch for me? It has an update that fixes this issue locally for me in the environment I was able to recreate (I believe) your issue in.

**Comment by blackheaven** [comment] 2023-11-05 15:41
Hello @miversen33,

I'd like to apologize for the delay, I had two long days.

I have just tried your branch and it works!

Thanks a lot for your hard work (debugging and Sunglass in general).

Regards.

**Comment by miversen33** [comment] 2023-11-05 15:45
Perfect :) I will leave this branch up until the end of the weekend and it will be deleted tomorrow. I have merged it into main so you should be good on main now :)

**Closed** 2023-11-05 15:44 UTC
Labels: bug
